[package]
name = "unpack_node"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
tokio = { workspace = true }
unpack_core = { path = "../unpack_core" }

[build-dependencies]
napi-build = { workspace = true }
